name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GAME_VERSION: EMERALD
      GAME_REVISION: 0
      GAME_LANGUAGE: ENGLISH
      MODERN: 0
      COMPARE: 0
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Checkout agbcc
        uses: actions/checkout@master
        with:
          path: agbcc
          repository: pret/agbcc

      - name: Install binutils
        run: |
          sudo apt install -y gcc-arm-none-eabi binutils-arm-none-eabi libpng-dev libelf-dev
        # build-essential and git are already installed
        # gcc-arm-none-eabi is only needed for the modern build
        # as an alternative to dkP
        
      - name: Install Dependencies
        run: |
          ./init_deps.sh

      - name: Install agbcc
        run: |
          ./build.sh
          ./install.sh ../
        working-directory: agbcc

      - name: Modern
        env:
          MODERN: 1
          COMPARE: 0
          RELEASE: 1
        run: make -j${nproc} -O all

      - uses: actions/upload-artifact@v4
        with:
            name: emerogue
            path: emerogue.gba
            retention-days: 1
  
      - uses: actions/upload-artifact@v4
        with:
            name: emerogue_elf
            path: emerogue.elf
            retention-days: 1
            
      - uses: actions/upload-artifact@v4
        with:
            name: emerogue_map
            path: emerogue.map
            retention-days: 1
